{{- if .Values.auth.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: registry-htpasswd
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: vault-kv
    kind: ClusterSecretStore

  target:
    name: registry-htpasswd
    creationPolicy: Owner

  data:
    - secretKey: HTPASSWD
      remoteRef:
        key: apps/registry
        property: HTPASSWD
{{- end }}
