apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: registry
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  selector:
    app: registry
  ports:
    - name: registry
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.ports.containerPort }}
