apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-secrets
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: vault-kv
    kind: ClusterSecretStore

  target:
    name: minio-secrets
    creationPolicy: Owner

  data:
    - secretKey: MINIO_ROOT_USER
      remoteRef:
        key: apps/minio
        property: MINIO_ROOT_USER

    - secretKey: MINIO_ROOT_PASSWORD
      remoteRef:
        key: apps/minio
        property: MINIO_ROOT_PASSWORD
