apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-api
  namespace: {{ .Values.namespace }}
  annotations:
    cert-manager.io/cluster-issuer: sesc-internal-issuer
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - {{ include "cluster.fqdn" (dict "ctx" . "prefix" .Values.apiHostPrefix) | quote }}
      secretName: {{ .Values.tlsSecretName }}
  rules:
    - host: {{ include "cluster.fqdn" (dict "ctx" . "prefix" .Values.apiHostPrefix) | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: minio
                port:
                  number: {{ .Values.apiPort }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-console
  namespace: {{ .Values.namespace }}
  annotations:
    cert-manager.io/cluster-issuer: sesc-internal-issuer
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - {{ include "cluster.fqdn" (dict "ctx" . "prefix" .Values.consoleHostPrefix) | quote }}
      secretName: {{ .Values.tlsSecretName }}-console
  rules:
    - host: {{ include "cluster.fqdn" (dict "ctx" . "prefix" .Values.consoleHostPrefix) | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: minio
                port:
                  number: {{ .Values.consolePort }}
