apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: minio
spec:
  type: ClusterIP
  selector:
    app: minio
  ports:
    - name: api
      port: {{ .Values.apiPort }}
      targetPort: api
    - name: console
      port: {{ .Values.consolePort }}
      targetPort: console
