apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentik-worker
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "authentik.labels" . | nindent 4 }}
    component: worker
spec:
  replicas: {{ .Values.authentik.workerReplicas }}
  selector:
    matchLabels:
      app: authentik-worker
  template:
    metadata:
      labels:
        app: authentik-worker
        {{- include "authentik.labels" . | nindent 8 }}
    spec:
      volumes:
        - name: blueprints
          configMap:
            name: authentik-blueprints
      containers:
        - name: authentik-worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - ak
            - worker

          env:
            - name: AUTHENTIK_REDIS__HOST
              value: authentik-redis

            - name: AUTHENTIK_POSTGRESQL__HOST
              value: authentik-postgres

            - name: AUTHENTIK_POSTGRESQL__PORT
              value: "5432"

            - name: AUTHENTIK_POSTGRESQL__NAME
              value: {{ .Values.postgres.database | quote }}

            - name: AUTHENTIK_POSTGRESQL__USER
              value: {{ .Values.postgres.user | quote }}

            - name: AUTHENTIK_BOOTSTRAP_EMAIL
              value: {{ .Values.authentik.adminEmail | quote }}

            - name: SPRAVKI_CLIENT_ID
              value: {{ .Values.authentik.clients.spravki.clientId | quote }}

            - name: SPRAVKI_REDIRECT_URI
              value: {{ printf "%s/auth/callback" (include "cluster.url" (dict "ctx" . "prefix" "spravki")) | quote }}

            - name: TECHNICAL_SUPPORT_CLIENT_ID
              value: {{ .Values.authentik.clients.technicalSupport.clientId | quote }}

            - name: TECHNICAL_SUPPORT_REDIRECT_URI
              value: {{ printf "%s/auth/callback" (include "cluster.url" (dict "ctx" . "prefix" "api.support")) | quote }}

            - name: AUTH_ADMIN_APP_CLIENT_ID
              value: {{ .Values.authentik.clients.authAdmin.clientId | quote }}

            - name: AUTH_ADMIN_APP_REDIRECT_URI
              value: {{ printf "%s/auth/callback" (include "cluster.url" (dict "ctx" . "prefix" "admin")) | quote }}

            - name: OPENFGA_CLIENT_ID
              value: {{ .Values.authentik.clients.openfga.clientId | quote }}

            - name: AUTHENTIK_ERROR_REPORTING__ENABLED
              value: {{ .Values.authentik.errorReportingEnabled | quote }}

          envFrom:
            - secretRef:
                name: authentik-secrets

          volumeMounts:
            - name: blueprints
              mountPath: /blueprints/mounted/authentik-blueprints
              readOnly: true

          resources:
            {{- toYaml .Values.authentik.resources.worker | nindent 12 }}