apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-secrets
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: vault-kv
    kind: ClusterSecretStore

  target:
    name: authentik-secrets
    creationPolicy: Owner

  data:
    - secretKey: PG_PASS
      remoteRef:
        key: apps/authentik
        property: PG_PASS

    - secretKey: AUTHENTIK_SECRET_KEY
      remoteRef:
        key: apps/authentik
        property: AUTHENTIK_SECRET_KEY

    - secretKey: AUTHENTIK_ADMIN_EMAIL
      remoteRef:
        key: apps/authentik
        property: AUTHENTIK_ADMIN_EMAIL

    - secretKey: AUTHENTIK_ADMIN_PASSWORD
      remoteRef:
        key: apps/authentik
        property: AUTHENTIK_ADMIN_PASSWORD

    - secretKey: SPRAVKI_CLIENT_ID
      remoteRef:
        key: apps/authentik
        property: SPRAVKI_CLIENT_ID

    - secretKey: SPRAVKI_CLIENT_SECRET
      remoteRef:
        key: apps/authentik
        property: SPRAVKI_CLIENT_SECRET

    - secretKey: SA_SPRAVKI_APP_PASSWORD
      remoteRef:
        key: apps/authentik
        property: SA_SPRAVKI_APP_PASSWORD

    - secretKey: TECHNICAL_SUPPORT_CLIENT_ID
      remoteRef:
        key: apps/authentik
        property: TECHNICAL_SUPPORT_CLIENT_ID

    - secretKey: TECHNICAL_SUPPORT_CLIENT_SECRET
      remoteRef:
        key: apps/authentik
        property: TECHNICAL_SUPPORT_CLIENT_SECRET

    - secretKey: SA_TECHNICAL_SUPPORT_APP_PASSWORD
      remoteRef:
        key: apps/authentik
        property: SA_TECHNICAL_SUPPORT_APP_PASSWORD

    - secretKey: AUTH_ADMIN_APP_CLIENT_ID
      remoteRef:
        key: apps/authentik
        property: AUTH_ADMIN_APP_CLIENT_ID

    - secretKey: AUTH_ADMIN_APP_CLIENT_SECRET
      remoteRef:
        key: apps/authentik
        property: AUTH_ADMIN_APP_CLIENT_SECRET

    - secretKey: SA_AUTH_ADMIN_APP_APP_PASSWORD
      remoteRef:
        key: apps/authentik
        property: SA_AUTH_ADMIN_APP_APP_PASSWORD

    - secretKey: SA_AUTH_ADMIN_APP_API_TOKEN
      remoteRef:
        key: apps/authentik
        property: SA_AUTH_ADMIN_APP_API_TOKEN