{{- $host := include "cluster.fqdn" (dict "ctx" . "prefix" .Values.hostPrefix) }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vault
  annotations:
    cert-manager.io/cluster-issuer: sesc-internal-issuer
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - {{ $host | quote }}
      secretName: {{ .Values.tlsSecretName }}
  rules:
    - host: {{ $host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vault
                port:
                  number: 8200
