apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: redis-secrets
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: vault-kv
    kind: ClusterSecretStore

  target:
    name: redis-secrets
    creationPolicy: Owner

  data:
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: apps/redis
        property: REDIS_PASSWORD
