apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sesc-portal-secrets
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-kv
    kind: ClusterSecretStore
  target:
    name: sesc-portal-secrets
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: apps/sesc-portal
        property: POSTGRES_PASSWORD
    - secretKey: DATABASE_URL
      remoteRef:
        key: apps/sesc-portal
        property: DATABASE_URL
    - secretKey: SECRET_KEY
      remoteRef:
        key: apps/sesc-portal
        property: SECRET_KEY