apiVersion: v1
kind: Service
metadata:
  name: sesc-portal-postgres
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: sesc-portal-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sesc-portal-postgres
  namespace: {{ .Values.namespace }}
spec:
  serviceName: sesc-portal-postgres
  replicas: 1
  selector:
    matchLabels:
      app: sesc-portal-postgres
  template:
    metadata:
      labels:
        app: sesc-portal-postgres
    spec:
      containers:
        - name: postgres
          image: {{ .Values.postgres.image | quote }}
          ports:
            - name: postgres
              containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgres.database | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.postgres.user | quote }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sesc-portal-secrets
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: {{ .Values.postgres.storage.storageClass | quote }}
        resources:
          requests:
            storage: {{ .Values.postgres.storage.size | quote }}