apiVersion: v1
kind: Service
metadata:
  name: sesc-portal
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: sesc-portal
  ports:
    - name: http
      port: {{ .Values.port }}
      targetPort: http