namespace: spravki

global:
  internalCA:
    enabled: true
    configMapName: sesc-internal-ca
    mountPath: /etc/ssl/certs/sesc-internal-ca.crt

image:
  repository: spravki-frontend
  tag: "660b3b5"
  pullPolicy: IfNotPresent

hostPrefix: spravki
apiHostPrefix: spravki
tlsSecretName: spravki-frontend-tls

port: 80

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    memory: 128Mi
