namespace: spravki

image:
  repository: spravki-frontend
  tag: "a67cf1b"
  pullPolicy: IfNotPresent

hostPrefix: spravki
tlsSecretName: spravki-frontend-tls

port: 80

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    memory: 128Mi
