namespace: lyceum-auth-admin

frontendHostPrefix: admin
apiHostPrefix: admin
tlsSecretName: lyceum-auth-admin-tls


global:
  internalCA:
    enabled: true
    configMapName: sesc-internal-ca
    mountPath: /etc/ssl/certs/sesc-internal-ca.crt
    
auth:
  hostPrefix: auth
  applicationSlug: auth-admin-app

frontend:
  global:
    internalCA:
      enabled: true
      configMapName: sesc-internal-ca
      mountPath: /etc/ssl/certs/sesc-internal-ca.crt

  image:
    repository: lyceum-auth-admin-frontend
    tag: "fca579b"
    pullPolicy: IfNotPresent
  replicas: 1
  port: 4173
  env:
    VITE_AUTH_PATH: /auth
    VITE_AUTH_CALLBACK_PATH: /auth/callback   
    VITE_AUTH_SCOPES: openid profile offline_access auth:users:read auth:users:create auth:users:update auth:users:delete
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      memory: 128Mi

backend:
  image:
    repository: lyceum-auth-admin-backend
    tag: "9e16c52"
    pullPolicy: IfNotPresent
  replicas: 1
  port: 5000
  healthPath: /health
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      memory: 512Mi

externalSecret:
  enabled: true
  name: lyceum-auth-admin-secrets
  refreshInterval: 1h
  secretStoreRef:
    name: vault-kv
    kind: ClusterSecretStore
  remoteRef:
    key: apps/lyceum-auth-admin
  data:
    - secretKey: CLIENT_ID
      property: CLIENT_ID
    - secretKey: CLIENT_SECRET
      property: CLIENT_SECRET
