version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: infra-postgresql
    ports:
      - "${POSTGRES_PORTS}"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_NAME}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: unless-stopped
