apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: document-renderer-secrets
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: vault-kv
    kind: ClusterSecretStore

  target:
    name: document-renderer-secrets
    creationPolicy: Owner

  data:
    - secretKey: BUCKET_NAME
      remoteRef:
        key: apps/document-renderer
        property: BUCKET_NAME

    - secretKey: RABBITMQ_USER
      remoteRef:
        key: apps/rabbitmq
        property: RABBITMQ_USER

    - secretKey: RABBITMQ_PASSWORD
      remoteRef:
        key: apps/rabbitmq
        property: RABBITMQ_PASSWORD

    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: apps/redis
        property: REDIS_PASSWORD

    - secretKey: MINIO_ROOT_USER
      remoteRef:
        key: apps/minio
        property: MINIO_ROOT_USER

    - secretKey: MINIO_ROOT_PASSWORD
      remoteRef:
        key: apps/minio
        property: MINIO_ROOT_PASSWORD
