apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: technical-support-backend-secrets
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: vault-kv
    kind: ClusterSecretStore

  target:
    name: technical-support-backend-secrets
    creationPolicy: Owner

  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: apps/technical-support-backend
        property: POSTGRES_PASSWORD
