apiVersion: v1
kind: Service
metadata:
  name: technical-support-postgres
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: technical-support-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: technical-support-postgres
  namespace: {{ .Values.namespace }}
spec:
  serviceName: technical-support-postgres
  replicas: 1
  selector:
    matchLabels:
      app: technical-support-postgres
  template:
    metadata:
      labels:
        app: technical-support-postgres
    spec:
      containers:
        - name: postgres
          image: {{ .Values.postgres.image | quote }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgres.database | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.postgres.user | quote }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: technical-support-backend-secrets
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              memory: 512Mi
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: {{ .Values.postgres.storage.storageClass | quote }}
        resources:
          requests:
            storage: {{ .Values.postgres.storage.size | quote }}
