namespace: technical-support

image:
  repository: technical-support-backend
  tag: "9d793a4"
  pullPolicy: IfNotPresent

hostPrefix: support
tlsSecretName: technical-support-backend-tls

port: 8123

rootPath: /

postgres:
  image: postgres:16-alpine
  database: technical_support
  user: techsupport
  storage:
    size: 5Gi
    storageClass: local-path

auth:
  hostPrefix: auth

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    memory: 512Mi
