namespace: technical-support

global:
  internalCA:
    enabled: true
    configMapName: sesc-internal-ca
    mountPath: /etc/ssl/certs/sesc-internal-ca.crt

image:
  repository: technical-support-backend
  tag: "6017dbb"
  pullPolicy: IfNotPresent

hostPrefix: support
tlsSecretName: technical-support-backend-tls

port: 8123

rootPath: /

postgres:
  image: postgres:16-alpine
  database: technical_support
  user: techsupport
  storage:
    size: 5Gi
    storageClass: local-path

auth:
  hostPrefix: auth

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    memory: 512Mi
