namespace: sesc-portal

global:
  internalCA:
    enabled: true
    configMapName: sesc-internal-ca
    mountPath: /etc/ssl/certs/sesc-internal-ca.crt

image:
  repository: sesc-portal
  tag: "5e1d926"
  pullPolicy: IfNotPresent

hostPrefix: portal
tlsSecretName: sesc-portal-tls

port: 8000

postgres:
  image: postgres:16-alpine
  database: sesc
  user: sesc
  storage:
    size: 5Gi
    storageClass: local-path

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    memory: 512Mi