http:
  routers:
    auth:
      rule: "Host(`sesc-it-team.ru`)"
      service: auth
      entryPoints:
        - websecure
      tls: {}

  services:
    auth:
      loadBalancer:
        servers:
          - url: {{ expandenv "http://$AUTH_API_URL" }}

#          "http://host.docker.internal:8000"  # для локального dev
#
#          или "http://auth-api:8000" если в Docker сети

  middlewares:
    auth-redirect:
      redirectScheme:
        scheme: https
        permanent: true
