services:
  minio:
    image: quay.io/minio/minio:latest
    container_name: minio-server
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_REGION=${MINIO_REGION}
      - MINIO_BROWSER_REDIRECT_URL=${MINIO_BROWSER_REDIRECT_URL}
      - MINIO_SERVER_URL=${MINIO_SERVER_URL}
    volumes:
      - minio-data:/data
    restart: unless-stopped

volumes:
  minio-data:
    driver: local

networks:
  default:
    name: minio-network
    driver: bridge