apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "lyceum-auth.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-kv
    kind: ClusterSecretStore
  target:
    name: {{ include "lyceum-auth.fullname" . }}-secrets
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: prod/lyceum-auth
        property: POSTGRES_PASSWORD
    - secretKey: ADMIN_PASSWORD
      remoteRef:
        key: prod/lyceum-auth
        property: ADMIN_PASSWORD
    - secretKey: SA_AUTH_ADMIN_APP_API_TOKEN
      remoteRef:
        key: prod/lyceum-auth
        property: SA_AUTH_ADMIN_APP_API_TOKEN