{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "lyceum-auth.fullname" . }}-secrets
  labels:
    {{- include "lyceum-auth.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreRef.name }}
    kind: {{ .Values.externalSecret.secretStoreRef.kind }}
  target:
    name: {{ .Values.externalSecret.targetSecretName }}
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: {{ .Values.externalSecret.remoteRef.key | quote }}
        property: POSTGRES_PASSWORD
    - secretKey: ADMIN_PASSWORD
      remoteRef:
        key: {{ .Values.externalSecret.remoteRef.key | quote }}
        property: ADMIN_PASSWORD
    - secretKey: SA_AUTH_ADMIN_APP_API_TOKEN
      remoteRef:
        key: {{ .Values.externalSecret.remoteRef.key | quote }}
        property: SA_AUTH_ADMIN_APP_API_TOKEN
{{- end }}