{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "lyceum-auth.fullname" . }}-postgresql
  labels:
    {{- include "lyceum-auth.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  type: ClusterIP
  selector:
    {{- include "lyceum-auth.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
  ports:
    - name: postgresql
      port: {{ .Values.postgresql.service.port }}
      targetPort: postgresql
{{- end }}