apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rabbitmq-secrets
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: vault-kv
    kind: ClusterSecretStore

  target:
    name: rabbitmq-secrets
    creationPolicy: Owner

  data:
    - secretKey: RABBITMQ_USER
      remoteRef:
        key: apps/rabbitmq
        property: RABBITMQ_USER

    - secretKey: RABBITMQ_PASSWORD
      remoteRef:
        key: apps/rabbitmq
        property: RABBITMQ_PASSWORD

    - secretKey: RABBITMQ_ERLANG_COOKIE
      remoteRef:
        key: apps/rabbitmq
        property: RABBITMQ_ERLANG_COOKIE
