apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: internal-ca-bundle
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  project: default
  source:
    repoURL: https://github.com/SESC-IT-Team/SESC-IT-IaC.git
    targetRevision: HEAD
    path: argocd/resources/internal-ca-bundle
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true