apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lyceum-auth
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/SESC-IT-Team/SESC-IT-IaC.git
    targetRevision: HEAD
    path: apps/lyceum-auth

  destination:
    server: https://kubernetes.default.svc
    namespace: lyceum-auth

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true