# ArgoCD Application: RabbitMQ.
# Source: apps/rabbitmq/ (helm chart in this repo).
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/SESC-IT-Team/SESC-IT-IaC.git
    targetRevision: HEAD
    path: apps/rabbitmq
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: rabbitmq
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
