namespace: minio

image: quay.io/minio/minio:latest

apiHostPrefix: s3
consoleHostPrefix: minio

apiPort: 9000
consolePort: 9001

tlsSecretName: minio-tls

storage:
  size: 10Gi
  storageClass: local-path

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    memory: 512Mi
