apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: eso-vault-test
  namespace: external-secrets

spec:
  refreshInterval: 1h

  secretStoreRef:
    name: vault-kv
    kind: ClusterSecretStore

  target:
    name: eso-vault-test
    creationPolicy: Owner

  data:
    - secretKey: TEST_USERNAME
      remoteRef:
        key: apps/eso-test
        property: username

    - secretKey: TEST_PASSWORD
      remoteRef:
        key: apps/eso-test
        property: password