apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: spravki-backend-secrets
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: vault-kv
    kind: ClusterSecretStore

  target:
    name: spravki-backend-secrets
    creationPolicy: Owner

  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: apps/spravki-backend
        property: POSTGRES_PASSWORD

    - secretKey: RABBITMQ_PASSWORD
      remoteRef:
        key: apps/rabbitmq
        property: RABBITMQ_PASSWORD

    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: apps/redis
        property: REDIS_PASSWORD

    - secretKey: MINIO_ROOT_PASSWORD
      remoteRef:
        key: apps/minio
        property: MINIO_ROOT_PASSWORD

    - secretKey: CLIENT_SECRET
      remoteRef:
        key: apps/authentik
        property: SPRAVKI_CLIENT_SECRET
