apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spravki-backend
  namespace: {{ .Values.namespace }}
  annotations:
    cert-manager.io/cluster-issuer: sesc-internal-issuer
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
spec:
  ingressClassName: traefik
  tls:
    - hosts:
      - {{ printf "api.%s" (include "cluster.fqdn" (dict "ctx" . "prefix" .Values.hostPrefix)) | quote }}
      secretName: {{ .Values.tlsSecretName }}
  rules:
    - host: {{ printf "api.%s" (include "cluster.fqdn" (dict "ctx" . "prefix" .Values.hostPrefix)) | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: spravki-backend
                port:
                  number: {{ .Values.port }}
