apiVersion: v1
kind: Service
metadata:
  name: spravki-backend
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: spravki-backend
spec:
  type: ClusterIP
  selector:
    app: spravki-backend
  ports:
    - name: http
      port: {{ .Values.port }}
      targetPort: http
