global:
  enabled: true
  tlsDisable: true

server:
  image:
    repository: hashicorp/vault

  ha:
    enabled: true
    replicas: 1

    disruptionBudget:
      enabled: false

    raft:
      enabled: true
      setNodeId: true
      config: |
        ui = true

        listener "tcp" {
          tls_disable = 1
          address         = "[::]:8200"
          cluster_address = "[::]:8201"
        }

        storage "raft" {
          path    = "/vault/data"
          node_id = "vault-0"
        }

        service_registration "kubernetes" {}

  dataStorage:
    enabled: true
    size: 10Gi
    storageClass: local-path

  auditStorage:
    enabled: true
    size: 5Gi
    storageClass: local-path

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 768Mi

  ingress:
    enabled: true
    ingressClassName: traefik
    hostname: vault.sesc-it-team.ru
    tls:
      - hosts:
          - vault.sesc-it-team.ru
        secretName: vault-tls
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
      acme.cert-manager.io/http01-edit-in-place: "true"

ui:
  enabled: true
  serviceType: ClusterIP

injector:
  enabled: false